# **Tugas 7 : Klasifikasi Berita Metode Logistic Regression dengan reduksi dimensi**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/My Drive/PPW-A/report/Tugas-PPW/hasil_preprocesing.csv")
df.head()

,judul,isi,tanggal,kategori,Hasil cleansing,Hasil case_folding,tokenize,Hasil stopword
0,18 Tim yang Lolos FFWS Global Finals 2024 di B...,Jakarta - Rangkaian pertandingan di FFWS SEA 2...,"Rabu, 16 Okt 2024 19:30 WIB",Games,Jakarta Rangkaian pertandingan di FFWS SEA F...,jakarta rangkaian pertandingan di ffws sea f...,"['jakarta', 'rangkaian', 'pertandingan', 'di',...",jakarta rangkaian pertandingan ffws sea fall s...
1,Ampun Bang Jago! Zuckerberg Klaim Pemain Handa...,"Jakarta - CEO Meta Mark Zuckerberg, cukup perc...","Rabu, 16 Okt 2024 17:50 WIB",Games,Jakarta CEO Meta Mark Zuckerberg cukup percay...,jakarta ceo meta mark zuckerberg cukup percay...,"['jakarta', 'ceo', 'meta', 'mark', 'zuckerberg...",jakarta ceo meta mark zuckerberg percaya kemam...
2,"20 Game Horor Terbaik Tahun 2000an, Udah Perna...",Jakarta - Game horor selalu punya daya tarikny...,"Rabu, 16 Okt 2024 14:20 WIB",Games,Jakarta Game horor selalu punya daya tariknya...,jakarta game horor selalu punya daya tariknya...,"['jakarta', 'game', 'horor', 'selalu', 'punya'...",jakarta game horor daya tariknya penikmatnya b...
3,"Begini Cara Dapat Skin Zhou Yu HOK Gratis, Gam...",Jakarta - Ternyata cara dapat skin Zhou Yu Hon...,"Rabu, 16 Okt 2024 12:15 WIB",Games,Jakarta Ternyata cara dapat skin Zhou Yu Hono...,jakarta ternyata cara dapat skin zhou yu hono...,"['jakarta', 'ternyata', 'cara', 'dapat', 'skin...",jakarta skin zhou yu honor of kings hok gratis...
4,"Gagal Juara FFWS SEA 2024 Fall, Wakil RI: Kita...","Jakarta - Tampil di depan ribuan pendukungnya,...","Selasa, 15 Okt 2024 17:36 WIB",Games,Jakarta Tampil di depan ribuan pendukungnya t...,jakarta tampil di depan ribuan pendukungnya t...,"['jakarta', 'tampil', 'di', 'depan', 'ribuan',...",jakarta tampil ribuan pendukungnya wakil indon...

## **Label Encoder**

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Transformasi data kategorik
label_encoder = LabelEncoder()
df.loc[:, 'kategori_encoded'] = label_encoder.fit_transform(df['kategori'])

# Menampilkan nilai sebelum dan sesudah konversi
print("\nNilai sebelum dan sesudah konversi:")
print(dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

print("\nDataFrame setelah Label Encoding:")
df.head()

Nilai sebelum dan sesudah konversi:
{'Games': 0, 'Sepak Bola': 1}

DataFrame setelah Label Encoding:

,judul,isi,tanggal,kategori,Hasil cleansing,Hasil case_folding,tokenize,Hasil stopword,kategori_encoded
0,18 Tim yang Lolos FFWS Global Finals 2024 di B...,Jakarta - Rangkaian pertandingan di FFWS SEA 2...,"Rabu, 16 Okt 2024 19:30 WIB",Games,Jakarta Rangkaian pertandingan di FFWS SEA F...,jakarta rangkaian pertandingan di ffws sea f...,"['jakarta', 'rangkaian', 'pertandingan', 'di',...",jakarta rangkaian pertandingan ffws sea fall s...,0
1,Ampun Bang Jago! Zuckerberg Klaim Pemain Handa...,"Jakarta - CEO Meta Mark Zuckerberg, cukup perc...","Rabu, 16 Okt 2024 17:50 WIB",Games,Jakarta CEO Meta Mark Zuckerberg cukup percay...,jakarta ceo meta mark zuckerberg cukup percay...,"['jakarta', 'ceo', 'meta', 'mark', 'zuckerberg...",jakarta ceo meta mark zuckerberg percaya kemam...,0
2,"20 Game Horor Terbaik Tahun 2000an, Udah Perna...",Jakarta - Game horor selalu punya daya tarikny...,"Rabu, 16 Okt 2024 14:20 WIB",Games,Jakarta Game horor selalu punya daya tariknya...,jakarta game horor selalu punya daya tariknya...,"['jakarta', 'game', 'horor', 'selalu', 'punya'...",jakarta game horor daya tariknya penikmatnya b...,0
3,"Begini Cara Dapat Skin Zhou Yu HOK Gratis, Gam...",Jakarta - Ternyata cara dapat skin Zhou Yu Hon...,"Rabu, 16 Okt 2024 12:15 WIB",Games,Jakarta Ternyata cara dapat skin Zhou Yu Hono...,jakarta ternyata cara dapat skin zhou yu hono...,"['jakarta', 'ternyata', 'cara', 'dapat', 'skin...",jakarta skin zhou yu honor of kings hok gratis...,0
4,"Gagal Juara FFWS SEA 2024 Fall, Wakil RI: Kita...","Jakarta - Tampil di depan ribuan pendukungnya,...","Selasa, 15 Okt 2024 17:36 WIB",Games,Jakarta Tampil di depan ribuan pendukungnya t...,jakarta tampil di depan ribuan pendukungnya t...,"['jakarta', 'tampil', 'di', 'depan', 'ribuan',...",jakarta tampil ribuan pendukungnya wakil indon...,0

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
# Memisahkan fitur dan label
x = df['Hasil stopword']
y = df['kategori_encoded']

## **Split Data**

In [ ]:
# Membagi data menjadi data latih dan data uji
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

## **TF-IDF (Term Frequency-Inverse Document Frequency)**

In [ ]:
# Tahap 1: TF-IDF
tfidf_vectorizer = TfidfVectorizer()
x_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
x_test_tfidf = tfidf_vectorizer.transform(x_test)

# Mengonversi hasil TF-IDF menjadi DataFrame
df_train_tfidf = pd.DataFrame(x_train_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
df_test_tfidf = pd.DataFrame(x_test_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
print("Hasil TF-IDF (Data Latih):")
df_train_tfidf

Hasil TF-IDF (Data Latih):

,aaa,abaaax,abaay,abdulla,abduweli,abduwelli,about,absen,abu,ac,...,zero,zhang,zhou,zombie,zona,zone,zoo,zubimendi,zuckerberg,zwolle
0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.031812,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.00000,0.0,0.0,0.061121,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
76,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
77,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
78,0.0,0.0,0.0,0.0,0.214021,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.19586,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
79,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.00000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0

## **Reduksi Dimensi (SVD)**

In [ ]:
# Tahap 2: SVD (Reduksi Dimensi)
svd = TruncatedSVD(n_components=100, random_state=42)  # Sesuaikan n_components dengan kebutuhan
x_train_svd = svd.fit_transform(x_train_tfidf)
x_test_svd = svd.transform(x_test_tfidf)

# Mengonversi hasil SVD menjadi DataFrame
df_train_svd = pd.DataFrame(x_train_svd)
df_test_svd = pd.DataFrame(x_test_svd)
print("\nHasil SVD (Data Latih):")
df_train_svd

Hasil SVD (Data Latih):

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,0.058963,-0.015123,0.063993,0.034103,0.059956,-0.005839,0.044069,-0.051077,0.080954,0.207889,...,-0.012331,-0.017466,-0.004468,0.002898,0.014131,0.002974,0.000922,0.001000,-0.010063,-0.000095
1,0.159630,0.062160,0.030261,0.010593,0.096343,0.216922,0.087037,-0.011854,0.723255,-0.271484,...,-0.270946,0.086570,-0.002425,-0.032870,0.002473,-0.018332,-0.002026,-0.001458,-0.005946,0.001110
2,0.095606,-0.102000,-0.064091,0.693701,-0.112359,-0.209831,-0.406132,0.158731,0.135374,0.016102,...,-0.003264,-0.004789,-0.006973,-0.005739,0.001196,-0.001502,-0.001060,-0.007255,0.002099,-0.217305
3,0.070058,-0.048773,-0.024627,0.250733,0.017777,0.071244,0.249669,-0.066463,-0.056826,-0.027197,...,0.000551,0.004854,0.002135,0.004962,-0.000698,-0.000836,-0.001311,0.000049,0.000168,0.004786
4,0.440172,0.263826,0.077392,-0.019132,-0.038698,0.041608,-0.035825,0.066354,-0.098866,-0.000120,...,-0.013019,-0.021704,-0.015830,0.003487,-0.025330,-0.006394,0.009847,0.001468,-0.000783,-0.000307
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.127649,-0.415413,0.778325,-0.026442,-0.073670,-0.000048,-0.003828,0.014209,-0.016107,-0.045019,...,-0.011850,-0.188951,-0.027019,-0.000447,0.004411,0.020178,0.359209,0.021810,-0.108801,-0.001911
76,0.064667,0.016641,0.069894,0.041070,0.741129,-0.152516,-0.110622,-0.011853,-0.119008,-0.134343,...,-0.000554,-0.089217,0.017739,-0.002278,-0.027008,0.000291,-0.009666,0.001382,-0.012981,0.000527
77,0.482129,-0.500240,-0.342646,-0.190956,-0.008485,-0.156752,0.067596,0.111547,0.030793,-0.011397,...,-0.009582,0.004024,0.020964,-0.161516,0.025076,0.363315,-0.019695,0.100070,0.002759,-0.005927
78,0.391870,0.328685,0.102746,-0.021590,-0.095903,-0.195247,0.043103,-0.122956,0.014528,-0.032423,...,-0.040661,-0.006938,-0.005301,0.007563,-0.001752,-0.010537,-0.002758,-0.002702,-0.003008,-0.000495
79,0.106645,0.010389,0.095812,0.053561,0.727563,-0.122506,-0.095378,-0.001302,-0.064177,-0.125809,...,-0.010444,0.046977,0.010520,0.006162,0.017497,0.005202,0.010792,-0.002452,0.002132,0.000208

## **Model Logistic Regression**

In [ ]:
# Tahap 3: Klasifikasi dengan Logistic Regression
clf = LogisticRegression(random_state=42,max_iter=1000, C=0.2)
clf.fit(x_train_svd, y_train)
y_pred = clf.predict(x_test_svd)

In [ ]:
# Evaluasi Model
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9
              precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.80      1.00      0.89         8

    accuracy                           0.90        20
   macro avg       0.90      0.92      0.90        20
weighted avg       0.92      0.90      0.90        20

In [ ]:
# Simpan TF-IDF vectorizer dan model
import pickle

with open('svd_tfidf.pkl', 'wb') as tfidf_file:
    pickle.dump(x_train_svd, tfidf_file)

with open('logistic_regression_model.pkl', 'wb') as model_file:
    pickle.dump(clf, model_file)

## **Pengujian**

In [ ]:
import joblib
from sklearn.pipeline import Pipeline

# Misalnya, Anda telah membuat pipeline
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('svd', TruncatedSVD(n_components=100)),
    ('clf', LogisticRegression())
])

# Setelah melatih model
pipeline.fit(x_train, y_train)

# Menyimpan pipeline
joblib.dump(pipeline, 'svd_tfidf_pipeline.pkl')

['svd_tfidf_pipeline.pkl']

In [ ]:
# Teks baru yang ingin diprediksi
new_text_1 = ['''
Jakarta - Game horor selalu punya daya tariknya sendiri, sehingga membuat sebagian penikmatnya betah memainkannya dalam waktu yang lama. Beberapa dari mereka ada yang kecanduan dengan nuansa mencekamnya, atau penasaran dengan alur ceritanya. Namun memang tidak semua gamer bisa mengonsumsi kengerian yang diberikan para pengembang game horor. Tak sedikit dari mereka yang menghindari visual menyeramkannya, atau suara kejutan yang bisa menyiksa jantung para pemainnya. Namun memang hal itu lah yang menjadi pembeda antara game horor dengan genre lainnya. Meski tidak selalu menawarkan adegan bertarung dengan penuh gaya, genre yang satu ini punya siasat lain dalam upaya memberikan keseruan kepada para pemain. Nah dari sekian banyak game horor yang telah dirilis oleh para pengembang di luar sana, gamer sudah main apa saja? Pasti Resident Evil menjadi salah satu favorit sepanjang masa. Tapi tahukah detikers, tidak hanya seri Resident Evil yang dapat memberikan keseruan dalam bermain game horor. Banyak sekali gamer horor terbaik yang diluncurkan sepanjang tahun 2000an. Hampir semuanya bagus, dan layak dicoba. Jadi apa game horor terbaik tahun 2000an yang sudah pernah kalian mainkan? Pasti ada beberapa judul yang melekat di hati kalian, karena menjadi pemicu kecintaan terhadap genre seram ini. Di sini, detikINET sudah mengumpulkan 20 game horor terbaik tahun 2000an , yang bisa kalian coba mainkan. Itu pun kalau kalian merasa menjadi pemain paling berani. Berikut informasinya, sebagaimana dihimpun dari The Gamer, Rabu (16/10/2024). Game Horor Terbaik Tahun 2000an 1. Call Of Cthulhu: Dark Corners Of The Earth Platform: PC dan Xbox Pengembang: Headfirst Productions Penerbit: Bethesda Softworks dan 2K Games 2. The Suffering Platform: PC, PS2, dan Xbox Pengembang: Surreal Software Penerbit: Midway Games dan Zoo Digital Publishing 3. Cold Fear Platform: PC, PS2, dan Xbox Pengembang: Darkworks Penerbit: Ubisoft 4. Siren Platform: PS3 dan PS4 Pengembang: Japan Studio Penerbit: Sony Computer Entertainment 5. Martian Gothic: Unification Platform: PC dan PlayStation Pengembang: Creative Reality Penerbit: TalonSoft, Take-Two Interactive, Buka Entertainment, dan Take-Two Interactive Software Europe Ltd 6. Clive Barker's Undying Platform: PC Pengembang: DreamWorks Interactive dan Westlake Interactive Penerbit: Electronic Arts dan Aspyr 7. Penumbra: Overture Platform: PC Pengembang: Frictional Games Penerbit: Frictional Games 8. Saw: The Video Game Platform: PS3, Xbox 360, dan Microsoft Windows Pengembang: Zombie Studios Penerbit: Konami dan Brash Entertainment 9. Obscure Platform: PC. PS2, dan Xbox Pengembang: Hydravision Entertainment Penerbit: DreamCatcher Interactive 10. F.E.A.R. Platform: PC, PS3, dan Xbox 360 Pengembang: Monolith Productions Penerbit: Vivendi Universal 11. Haunting Ground Platform: PS2 dan PS3 Pengembang: Capcom Penerbit: Capcom 12. Dead Rising Platform: PC, PS4, Xbox 360, dan Xbox One Pengembang: Capcom Penerbit: Capcom 13. Condemned: Criminal Origins Platform: PC dan Xbox 360 Pengembang: Monolith Productions Penerbit: Sega 14. Fatal Frame 2: Crimson Butterfly Platform: PS2, PS3, Wii, dan Xbox Pengembang: Tecmo Penerbit: Tecmo 15. Eternal Darkness: Sanity's Requiem Platform: GameCube Pengembang: Silicon Knights Penerbit: Nintendo 16. Dead Space Platform: PC, PS3, dan Xbox 360 Pengembang: Visceral Games Penerbit: Electronic Arts 17. BioShock Platform: PC, PS3, dan Xbox 360 Pengembang: Irrational Games Penerbit: 2K Games 18. Resident Evil 4 Platform: PS4, PS3, PS2, Xbox One, Xbox 360, Switch, Wii, Nintendo GameCube, PC, Android, dan iOS Pengembang: Capcom Penerbit: Capcom 19. Resident Evil (2002) Platform: GameCube dan Wii Pengembang: Capcom Production Studio 4 Penerbit: Capcom 20. Silent Hill 2, 3, And 4 Platform: PC, PS2, PS3, Xbox, dan Xbox 360 Pengembang: Konami Penerbit: Konami (hps/fay)
''']

new_text_2 = ['''
Manchester - Paul Gascoigne menyarankan Marcus Rashford pindah ke Italia. Beberapa pemain yang redup bersama Manchester United kerap kali menemuikan sinarnya di Serie A . Marcus Rashford banyak dikritik usai tampil buruk bersama MU di awal musim ini. Ia baru mampu mengemas satu gol di Liga Inggris musim ini. Buruknya perfoma Rashford turut mempengaruhi laju MU. Setan Merah jeblok dengan berada di peringkat ke-14 dengan baru meraih delapan angka. Legenda Inggris, Paul Gascoigne, menyarankan Rashford pindah ke Serie A melihat situasi yang dihadapinya di MU. Ia menilai Rashford saat ini telah kehilangan kebahagiaan saat bermain bola. Gascoigne yakin Rashford bakal menemukan kembali kebahagian itu jika bermain Italia. Gascoigne sendiri pernah bermain di Serie A bersama Lazio pada rentang 1992-1995 usai pindah dari Tottenham Hotspur. Beberapa mantan pemain MU juga berhasil bersinar lagi usai pindah ke Serie A. Sebut saja Chris Smalling, Romelu Lukaku, dan teranyar Scott McTominay. McTominay yang banyak dikritik di MU justru jadi andalan Napoli di musim ini. "Saya suka Rashford, saya pikir dia pemain yang luar biasa, tetapi dia tampaknya memperhatikan itu," kata Gascoigne kepada SportsCasting. "Bahkan ketika dia mencetak gol, dia tampak tidak senang dengan hal itu, jadi ada sesuatu yang terjadi di sana." "Jika itu masalahnya, pindah saja. Anda mendapatkan beberapa pemain yang pindah dan kemudian mereka menemukan sesuatu yang berbeda. Untuk Rashford, dia tampaknya tidak senang bermain di Inggris. Dan beberapa klub bagus akan datang untuknya. Pergi ke Italia, itu akan mengejutkannya," jelasnya. (pur/krs)
''']

# Gabungkan kedua teks menjadi satu list
new_text = new_text_1 + new_text_2

# Melakukan prediksi dengan pipeline
predictions = pipeline.predict(new_text)

# Hasil prediksi
predicted_categories = ["Games" if prediction == 0 else "Sepak Bola" for prediction in predictions]

# Output hasil prediksi untuk masing-masing teks
for i, category in enumerate(predicted_categories):
    print(f"Prediksi untuk teks {i+1}: {category}")

Prediksi untuk teks 1: Games
Prediksi untuk teks 2: Sepak Bola